### ISSUE TITLE
No module named gevent

### ISSUE THREAD

**Issue by Beyarz** [DanMcInerney/elite-proxy-finder#17]
Command:
py -2.7 elite-proxy-finder.py

Error:
Traceback (most recent call last):
  File "elite-proxy-finder.py", line 15, in <module>
    from gevent import monkey
ImportError: No module named gevent

I installed gevent using this command "Pip install gevent" but I still get the error.

**Comment by dok852** [comment]
The fact that you're using "py -2.7" suggests that your default version is Python 3, thus you probably used the Python 3 pip which has installed it into the wrong version.
