### ISSUE TITLE
No module named BeautifulSoup

### ISSUE THREAD

**Issue by JL01152** [DanMcInerney/elite-proxy-finder#18]
I tried to run your code and received the following error. Is this still active?

dirtynix@dirtynix:~/Desktop$ python elite-proxy-finder.py -q
Traceback (most recent call last):
  File "elite-proxy-finder.py", line 24, in <module>
    from BeautifulSoup import BeautifulSoup
  File "/home/dirtynix/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named BeautifulSoup

**Comment by Beyarz** [comment]
Try from bs4 import BeautifulSoup.

**Comment by HoussemCharf** [comment]
`"from BeautifulSoup import BeautifulSoup" change it to "from bs4 import BeautifulSoup"`

**Comment by JL01152** [comment]
tried it and it works.. you guys are geniuses. Let me see how the code runs. I'm waiting on an output now

**Comment by JL01152** [comment]
dirtynix@dirtynix:~/Desktop$ gedit elite-proxy-finder.py 
dirtynix@dirtynix:~/Desktop$ python elite-proxy-finder.py 
[*] Your accurate external IP: ***.***.***.***
Traceback (most recent call last):
  File "elite-proxy-finder.py", line 400, in <module>
    P.run()
  File "elite-proxy-finder.py", line 64, in run
    gatherproxy_list = self.gatherproxy_req()
  File "elite-proxy-finder.py", line 182, in gatherproxy_req
    gatherproxy_list = self.parse_gp(lines)
  File "elite-proxy-finder.py", line 195, in parse_gp
    hex_port = l.split("'")[1]
IndexError: list index out of range
dirtynix@dirtynix:~/Desktop$

**Comment by HoussemCharf** [comment]
this project is abanded for quite some time if you need live proxies take a look at a code i wrote a while ago` https://github.com/HoussemCharf/FunUtils/blob/master/newproxy.py`

**Comment by DanMcInerney** [comment]
yeah this project was a pain in the ass because it just scraped 3 proxy sites so any time those sites changed their code even a smidge, it required code updates. Didn't feel worth it to me.
