### ISSUE TITLE
letushide.com is now offline

### ISSUE THREAD

**Issue by GuerrillaWarfare** [DanMcInerney/elite-proxy-finder#6]
The currently implemented proxy website previously known as "letushide.com" has now gone offline and has not been seen online for sometime now. elite-proxy-finder still works as should but always spits out that it can not find any proxies on "letushide.com". 

Suggestion: Maybe replace the "letushide.com" implementation with a similar service ?

**Comment by DanMcInerney** [comment]
Thanks for the notification. Will remove or replace when time is found, probably not for a while.
