### ISSUE TITLE
TypeError: __str__ returned non-string

### ISSUE THREAD

**Issue by marcotuna** [DanMcInerney/elite-proxy-finder#9]
I get a bunch of errors like this:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "elite-proxy-finder.py", line 247, in proxy_checker_req
    time_or_error = self.error_handler(str(e))
TypeError: __str__ returned non-string (type Error)
<Greenlet at 0x7786ea65cc30: <bound method find_http_proxy.proxy_checker_req of <__main__.find_http_proxy instance at 0x7786ea96fe18>>('109.236.81.101:35088')> failed with TypeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "elite-proxy-finder.py", line 247, in proxy_checker_req
    time_or_error = self.error_handler(str(e))
TypeError: __str__ returned non-string (type SysCallError)
<Greenlet at 0x7786ea654370: <bound method find_http_proxy.proxy_checker_req of <__main__.find_http_proxy instance at 0x7786ea96fe18>>('183.219.20.196:8123')> failed with TypeError

**Comment by DanMcInerney** [comment]
I can't reproduce this. I'm thinking that means it's probably a library installalation/version issue and since it's happening in greenlet.py, can you check what version of gevent you have? 

```pip freeze | grep gevent```

I'm using 0.13.6 on Kali.

**Comment by marcotuna** [comment]
Hi, I am using Debian 8.
When I type pip freeze | grep gevent I get the following:
gevent==1.0.1

**Comment by DanMcInerney** [comment]
Thanks, I'll upgrade and try again when I get a moment today or tomorrow.

**Comment by marcotuna** [comment]
Hi, I type:
pip install gevent --upgrade and now I have the version 1.0.2 but the problem still persists.
Thanks.

**Comment by DanMcInerney** [comment]
I just upgraded gevent to 1.1a2 and can't reproduce. What version of greenlet do you have?

I'm at:
```pip freeze | grep greenlet
greenlet==0.4.7```

**Comment by marcotuna** [comment]
Hi, I have the same version, 0.4.7.

**Comment by DanMcInerney** [comment]
Helpful screenshot. Seems this might be a problem with the requests (technically a problem with urllib3, but requests uses a packaged version of urllib3). https://github.com/shazow/urllib3/issues/556

What version of requests are you on?

I'm on: requests==2.6.0

**Comment by marcotuna** [comment]
urllib3==1.10.4
requests==2.7.0

Here is the complete list: http://pastebin.com/wjwwguAF

**Comment by DanMcInerney** [comment]
I can't really figure this out, I upgraded requests to 2.7.0, installed urllib3 1.11 and I still can't reproduce. I am on python 2.7.3 though.
